*** Variables ***

${IOS_LOGIN_OPTION}    accessibility_id=Login
${IOS_SIGN_UP_OPTION}   css=*[name="Sign up"]
${IOS_EMAIL_FIELD}    accessibility_id=input-email
${IOS_PASSWORD_FIELD}    accessibility_id=input-password
${IOS_REPEAT_PASSWORD_FIELD}    accessibility_id=input-repeat-password
${IOS_SIGNUP_BTN}    css=*[name="Sign up"]
${IOS_SUCCESS_TXT}    css=*[name="You successfully signed up!"]
${IOS_OK_BTN}    accessibility_id=OK