*** Variables ***

${ANDROID_LOGIN_OPTION}    accessibility_id=Login
${ANDROID_SIGN_UP_OPTION}    xpath=//*[@text="Sign up"]
${ANDROID_EMAIL_FIELD}    accessibility_id=input-email
${ANDROID_PASSWORD_FIELD}    accessibility_id=input-password
${ANDROID_PASSWORD_REPEAT_FIELD}    accessibility_id=input-repeat-password
${ANDROID_SIGNUP_BTN}    xpath=//*[@text="Sign up"]
${ANDROID_SUCCESS_TXT}    css=*[name="You successfully signed up!"]
${ANDROID_OK_BTN}    accessibility_id=OK